-- Peptides4Pets research-commerce backbone.
-- Keeps the pet customer journey isolated while reusing the existing order
-- and EFT settlement infrastructure.

create table if not exists public.psa_pets_checkout_consents (
  id bigint generated by default as identity primary key,
  order_id uuid not null unique references public.orders(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete restrict,
  policy_version text not null check (char_length(policy_version) between 1 and 80),
  report_scope_version text not null check (char_length(report_scope_version) between 1 and 80),
  age_confirmed boolean not null check (age_confirmed),
  nutritional_scope_acknowledged boolean not null check (nutritional_scope_acknowledged),
  label_use_acknowledged boolean not null check (label_use_acknowledged),
  report_scope_acknowledged boolean not null check (report_scope_acknowledged),
  marketing_consent boolean not null default false,
  client_accepted_at timestamptz not null,
  accepted_at timestamptz not null default now(),
  statements jsonb not null default '{}'::jsonb check (jsonb_typeof(statements) = 'object'),
  source text not null default 'pets_checkout' check (char_length(source) between 1 and 80)
);

create index if not exists psa_pets_checkout_consents_user_accepted_idx
  on public.psa_pets_checkout_consents (user_id, accepted_at desc);

alter table public.psa_pets_checkout_consents enable row level security;

create policy psa_pets_checkout_consents_owner_or_admin_select
on public.psa_pets_checkout_consents
for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select public.has_role((select auth.uid()), 'admin'::public.app_role))
);

revoke all on table public.psa_pets_checkout_consents from anon, authenticated;
grant select on table public.psa_pets_checkout_consents to authenticated;
grant all on table public.psa_pets_checkout_consents to service_role;
grant usage, select on sequence public.psa_pets_checkout_consents_id_seq to service_role;

create table if not exists public.psa_pets_order_details (
  order_id uuid primary key references public.orders(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete restrict,
  pet_name text not null check (char_length(btrim(pet_name)) between 1 and 120),
  pet_species text not null check (pet_species in ('dog', 'cat', 'horse')),
  storefront text not null default 'pets.peptide-south-africa.com'
    check (storefront = 'pets.peptide-south-africa.com'),
  created_at timestamptz not null default now()
);

create index if not exists psa_pets_order_details_user_created_idx
  on public.psa_pets_order_details (user_id, created_at desc);

alter table public.psa_pets_order_details enable row level security;

create policy psa_pets_order_details_owner_or_admin_select
on public.psa_pets_order_details
for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select public.has_role((select auth.uid()), 'admin'::public.app_role))
);

revoke all on table public.psa_pets_order_details from anon, authenticated;
grant select on table public.psa_pets_order_details to authenticated;
grant all on table public.psa_pets_order_details to service_role;

create table if not exists public.psa_pets_lifecycle_events (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  event text not null check (event in (
    'pets_catalog_viewed',
    'pets_research_navigator_started',
    'pets_research_navigator_completed',
    'pets_evidence_opened',
    'pets_waitlist_started',
    'pets_waitlist_joined',
    'pets_collagen_added',
    'pets_checkout_started',
    'pets_checkout_consent_accepted',
    'pets_marketing_consent_granted',
    'pets_order_created',
    'pets_eft_instructions_shown',
    'pets_portal_viewed',
    'pets_portal_orders_viewed',
    'pets_portal_reports_viewed',
    'pets_reorder_started'
  )),
  event_version text not null default '1.0' check (char_length(event_version) between 1 and 40),
  source text not null default 'pets_storefront' check (char_length(source) between 1 and 80),
  session_id text not null check (char_length(session_id) between 1 and 200),
  user_id uuid references auth.users(id) on delete set null,
  order_id uuid references public.orders(id) on delete set null,
  props jsonb not null default '{}'::jsonb
    check (jsonb_typeof(props) = 'object' and octet_length(props::text) <= 8192)
);

create index if not exists psa_pets_lifecycle_events_created_idx
  on public.psa_pets_lifecycle_events (created_at desc);
create index if not exists psa_pets_lifecycle_events_event_created_idx
  on public.psa_pets_lifecycle_events (event, created_at desc);
create index if not exists psa_pets_lifecycle_events_user_created_idx
  on public.psa_pets_lifecycle_events (user_id, created_at desc)
  where user_id is not null;
create index if not exists psa_pets_lifecycle_events_order_idx
  on public.psa_pets_lifecycle_events (order_id)
  where order_id is not null;

alter table public.psa_pets_lifecycle_events enable row level security;

create policy psa_pets_lifecycle_events_anon_insert
on public.psa_pets_lifecycle_events
for insert
to anon
with check (
  event in (
    'pets_catalog_viewed',
    'pets_research_navigator_started',
    'pets_research_navigator_completed',
    'pets_evidence_opened',
    'pets_waitlist_started',
    'pets_waitlist_joined',
    'pets_collagen_added',
    'pets_checkout_started'
  )
  and user_id is null
  and order_id is null
);

create policy psa_pets_lifecycle_events_authenticated_insert
on public.psa_pets_lifecycle_events
for insert
to authenticated
with check (
  (user_id is null or user_id = (select auth.uid()))
  and (
    order_id is null
    or exists (
      select 1 from public.orders
      where orders.id = psa_pets_lifecycle_events.order_id
        and orders.user_id = (select auth.uid())
    )
  )
);

create policy psa_pets_lifecycle_events_owner_or_admin_select
on public.psa_pets_lifecycle_events
for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select public.has_role((select auth.uid()), 'admin'::public.app_role))
);

revoke all on table public.psa_pets_lifecycle_events from anon, authenticated;
grant insert on table public.psa_pets_lifecycle_events to anon;
grant insert, select on table public.psa_pets_lifecycle_events to authenticated;
grant all on table public.psa_pets_lifecycle_events to service_role;

alter table public.psa_pets_waitlist
  add column if not exists research_information_acknowledged boolean not null default false,
  add column if not exists marketing_consent boolean not null default false,
  add column if not exists consent_version text,
  add column if not exists consent_accepted_at timestamptz;

create or replace function public.psa_pets_join_waitlist_v2(
  p_ticket_code text,
  p_owner_name text,
  p_email text,
  p_whatsapp text default null,
  p_pet_type text default null,
  p_pet_breed text default null,
  p_pet_age integer default null,
  p_city text default null,
  p_products jsonb default '[]'::jsonb,
  p_primary_concern text default null,
  p_referred_by text default null,
  p_source text default 'pets-landing',
  p_locale text default 'en',
  p_consent_popia boolean default false,
  p_research_information_acknowledged boolean default false,
  p_marketing_consent boolean default false,
  p_consent_version text default 'pets-research-interest-2026-09-01',
  p_utm jsonb default '{}'::jsonb,
  p_quiz_answers jsonb default null
)
returns table(ticket_code text, queue_number bigint)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ticket text;
begin
  if not p_consent_popia then
    raise exception 'POPIA processing acknowledgement is required' using errcode = '22023';
  end if;
  if not p_research_information_acknowledged then
    raise exception 'Research information acknowledgement is required' using errcode = '22023';
  end if;
  if char_length(btrim(coalesce(p_owner_name, ''))) < 2
     or char_length(p_owner_name) > 120 then
    raise exception 'Invalid owner name' using errcode = '22023';
  end if;
  if char_length(btrim(coalesce(p_email, ''))) > 320
     or btrim(coalesce(p_email, '')) !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then
    raise exception 'Invalid email address' using errcode = '22023';
  end if;
  if p_whatsapp is not null and char_length(p_whatsapp) > 32 then
    raise exception 'Invalid WhatsApp number' using errcode = '22023';
  end if;
  if p_pet_age is not null and (p_pet_age < 0 or p_pet_age > 80) then
    raise exception 'Invalid pet age' using errcode = '22023';
  end if;
  if jsonb_typeof(coalesce(p_products, '[]'::jsonb)) <> 'array' then
    raise exception 'Products must be an array' using errcode = '22023';
  end if;
  if char_length(coalesce(p_consent_version, '')) not between 1 and 80 then
    raise exception 'Invalid consent version' using errcode = '22023';
  end if;

  v_ticket := case
    when coalesce(p_ticket_code, '') ~ '^WL-PTD-[A-Z0-9]{4,12}$' then p_ticket_code
    else 'WL-PTD-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
  end;

  return query
  insert into public.psa_pets_waitlist (
    ticket_code, owner_name, email, whatsapp, pet_type, pet_breed, pet_age,
    city, products, primary_concern, referral_code, referred_by, source,
    locale, consent_popia, research_information_acknowledged,
    marketing_consent, consent_version, consent_accepted_at, utm, quiz_answers
  ) values (
    v_ticket, btrim(p_owner_name), lower(btrim(p_email)),
    nullif(btrim(coalesce(p_whatsapp, '')), ''),
    nullif(btrim(coalesce(p_pet_type, '')), ''),
    nullif(btrim(coalesce(p_pet_breed, '')), ''), p_pet_age,
    nullif(btrim(coalesce(p_city, '')), ''), coalesce(p_products, '[]'::jsonb),
    nullif(btrim(coalesce(p_primary_concern, '')), ''), v_ticket,
    nullif(btrim(coalesce(p_referred_by, '')), ''),
    left(coalesce(nullif(btrim(p_source), ''), 'pets-landing'), 80),
    case when p_locale in ('en', 'af') then p_locale else 'en' end,
    true, true, p_marketing_consent, p_consent_version, now(),
    coalesce(p_utm, '{}'::jsonb), p_quiz_answers
  )
  on conflict (email_normalized) do update set
    owner_name = excluded.owner_name,
    whatsapp = coalesce(excluded.whatsapp, public.psa_pets_waitlist.whatsapp),
    pet_type = coalesce(excluded.pet_type, public.psa_pets_waitlist.pet_type),
    pet_breed = coalesce(excluded.pet_breed, public.psa_pets_waitlist.pet_breed),
    pet_age = coalesce(excluded.pet_age, public.psa_pets_waitlist.pet_age),
    city = coalesce(excluded.city, public.psa_pets_waitlist.city),
    products = case when jsonb_array_length(excluded.products) > 0
      then excluded.products else public.psa_pets_waitlist.products end,
    primary_concern = coalesce(excluded.primary_concern, public.psa_pets_waitlist.primary_concern),
    referred_by = coalesce(public.psa_pets_waitlist.referred_by, excluded.referred_by),
    source = excluded.source,
    locale = excluded.locale,
    consent_popia = true,
    research_information_acknowledged = true,
    marketing_consent = public.psa_pets_waitlist.marketing_consent or excluded.marketing_consent,
    consent_version = excluded.consent_version,
    consent_accepted_at = excluded.consent_accepted_at,
    utm = public.psa_pets_waitlist.utm || excluded.utm,
    quiz_answers = coalesce(excluded.quiz_answers, public.psa_pets_waitlist.quiz_answers)
  returning psa_pets_waitlist.ticket_code, psa_pets_waitlist.queue_number;
end;
$$;

revoke all on function public.psa_pets_join_waitlist_v2(
  text, text, text, text, text, text, integer, text, jsonb, text, text, text,
  text, boolean, boolean, boolean, text, jsonb, jsonb
) from public;
grant execute on function public.psa_pets_join_waitlist_v2(
  text, text, text, text, text, text, integer, text, jsonb, text, text, text,
  text, boolean, boolean, boolean, text, jsonb, jsonb
) to anon, authenticated, service_role;

comment on table public.psa_pets_checkout_consents is
  'Immutable, versioned Peptides4Pets checkout acknowledgement receipts.';
comment on table public.psa_pets_order_details is
  'Pets-specific order metadata kept separate from human-store customer data.';
comment on table public.psa_pets_lifecycle_events is
  'First-party, Pets-only research-commerce lifecycle events.';
